update shjp

diff --git a/app/src/sh/shjp b/app/src/sh/shjp
--- a/app/src/sh/shjp
+++ b/app/src/sh/shjp
@@ -1,4 +1,5 @@
 #!/bin/bash
+version=v1.0.0
 
 # This software is released under the MIT License
 
@@ -65,6 +66,9 @@ function processShortOpt(){
             opt_flag=$(($opt_flag|1))
         elif [ "a$char" = ae ]; then
             opt_flag=$(($opt_flag|2))
+        elif [ "a$char" = av ]; then
+            echo $version
+            end 0
         elif [ "a$char" = ar ]; then
             argext_flag=2
             opt_flag=$(($opt_flag|4))
@@ -91,7 +95,6 @@ function setTargets(){
 }
 
 function extractValue(){
-
     input="$json_value_origin"
     if [ ${#targets[@]} -eq 0 ]; then
         echo "Arguments lack." >&2
@@ -99,13 +102,11 @@ function extractValue(){
     elif [ ! -f "$init_arg" ]; then
         if [ -n "$pipe_input" ]; then
             input="$pipe_input"
-            targets+=("$init_arg")
         else
             echo '-g option requires a file path as first argument, or pipe input.' >&2
             end 1
         fi
     fi
-
     for target in "${targets[@]}"; do
         echo "$input" |
         awk '{
@@ -157,6 +158,53 @@ function extractValue(){
     cat ${tmp}answer
 }
 
+declare -a targets=() str_shelf=() num_shelf=()
+opt_flag=0 # 1-compget/2-checkerr/4-recursive
+init_arg=''
+rcount=0
+argext_flag='' # 1-target/2-rec1/3-rec2
+
+if [ -p /dev/stdin ]; then
+    pipe_input="$(cat)"
+fi
+
+for arg in "$@"; do
+    if [ -n "$argext_flag" ]; then
+        if [ "$argext_flag" = 1 ]; then
+            setTargets "$arg"
+            argext_flag=''
+        elif [ "$argext_flag" = 2 ]; then
+            while read str; do 
+                str=${str//$CR/}
+                str=${str//$LF/}
+                str_shelf+=("$str")
+            done < <(cat "$arg")
+            argext_flag=3
+        elif [ "$argext_flag" = 3 ]; then
+            while read str; do 
+                str=${str//$CR/}
+                str=${str//$LF/}
+                num_shelf+=("$str")
+            done < <(cat "$arg")
+            argext_flag=''
+        fi
+    elif [[ "$arg" =~ ^-.+ ]]; then
+        processShortOpt "$arg"
+    elif [ -z "$init_arg" ]; then
+        init_arg="$arg"
+    fi
+done
+
+if [ -f "$init_arg" ]; then
+    json_value_origin="$(cat $init_arg)"
+else
+    json_value_origin="$init_arg"
+fi
+if [ $(($opt_flag&1)) != 0 ]; then
+    extractValue
+    end 0
+fi
+
 function printStacktrace() {
     index=1
     while frame=($(caller "${index}")); do
@@ -188,7 +236,6 @@ function checkLiteral(){
 }
 
 function identifyBracket(){
-
     if [ "$char" = '{' ]; then
         depth_counter=$depth_counter'{'
     elif [ "$char" = '['  ]; then
@@ -206,25 +253,41 @@ function identifyBracket(){
             invalidFormatError
         fi
     fi
-
     [ -n "$depth_counter" ] && flg_continue=1 || :
+}
+
+function readNum(){
+    if [[ "${json_value:$i:1}" =~ ^[0-9]$ ]]; then
+        flg_continue=1
+        return 0
+    fi
+    temp_num=${json_value:(($marked_idx-1)):(($i-$marked_idx+1))}
+    if [[ ! $temp_num =~ (^-?[1-9][0-9]*$|0) ]]; then
+        echo "Number as a value is invalid." >&2
+        echo "json ---> $json_value" >&2
+        echo "char at $i ---> $temp_num" >&2
+        end 1                
+    elif [ $jv_count != 0 ]; then
+        echo "$temp_num" >> ${tmp}num_shelf_${jv_count}
+    else
+        num_shelf+=("$temp_num")
+    fi
+    flg_on_read=''
+    flg_continue=''
+    pre_processed_jv_tmp+=$((num_idx_count++))
 }
 
 function preProcess(){
 
-    pre_processed_jv=''
-    pre_processed_jv_tmp=''
+    pre_processed_jv=''; pre_processed_jv_tmp='';
     json_value=${json_value_origin//$CR/}
     json_value=${json_value//$LF/}
-    flg_on_read='' # 1-str/2-literal
-    nr_index=0
-    jv_count=0
-    temp=''
-    literal=''
-    invalid=''
-    depth_counter=''
-    
-    for i in `seq 1 ${#json_value}`; do    
+    flg_on_read='' # 1-str/2-literal/3-num
+    str_idx_count=0; num_idx_count=0; jv_count=0;
+    temp=''; literal=''; invalid=''; depth_counter='';
+    length=${#json_value}
+
+    for i in `seq 1 $length`; do    
         char=${json_value:(($i-1)):1}
         if [ "$flg_on_read" = 1 ]; then
             [ "a$char" != 'a"' -o "a${json_value:(($i-2)):1}" = 'a\' ] && continue || :
@@ -234,12 +297,18 @@ function preProcess(){
                 str_shelf+=("${json_value:$marked_idx:(($i-$marked_idx-1))}")
             fi
             flg_on_read=''
-            pre_processed_jv_tmp+='"'$((nr_index++))
+            pre_processed_jv_tmp+='"'$((str_idx_count++))
         elif [ "$flg_on_read" = 2 ]; then 
             checkLiteral $literal
+        elif [ "$flg_on_read" = 3 ]; then 
+            readNum
         elif [ "$char" = '"' ]; then
             marked_idx=$i
             flg_on_read=1
+        elif [[ "$char" =~ ^[-0-9]$ ]]; then
+            marked_idx=$i
+            readNum
+            [ -n "$flg_continue" ] && flg_on_read=3 || :
         elif [ "$char" = 't' ]; then
             checkLiteral true
             literal=true
@@ -253,14 +322,13 @@ function preProcess(){
             literal=null
             flg_on_read=2
         elif [ "a$char" != "a " -a "a$char" != "a$TAB" ]; then
-            
             pre_processed_jv_tmp+=$char
             depth_counter_bf=$depth_counter
-            identifyBracket
-            
+            identifyBracket            
             if [ -z "$depth_counter" ]; then
-                if [[ -z $depth_counter_bf && ! "$char" =~ ^[0-9]+$ ]]; then
-                    echo "The inputs contain invalid value as below." >&2
+                if [ -z $depth_counter_bf ]; then
+                    echo "The input's file path isn't exist, and contains invalid value as json, as below." >&2
+                    echo "input as json ---> $json_value" >&2
                     echo "char at $i ---> $pre_processed_jv_tmp" >&2
                     end 1
                 elif [ -z "$pre_processed_jv" ]; then
@@ -268,7 +336,7 @@ function preProcess(){
                 else
                     jv_shelf+=("$pre_processed_jv_tmp")
                 fi
-                nr_index=0
+                str_idx_count=0; num_idx_count=0;
                 ((jv_count++))
                 pre_processed_jv_tmp=''
             fi
@@ -281,13 +349,32 @@ function callThis(){
     arg_jv="${jv_shelf[$((${1}-1))]}" 
     targets_combined=$(for t in "${targets[@]}"; do echo -n ${t},; done)
     if [ -e ${tmp}str_shelf_$1 ]; then # ignore arg_jv as literal
-        $0 "$arg_jv" -r ${tmp}str_shelf_$1 -t "${targets_combined:0:-1}" &
+        touch ${tmp}num_shelf_$1
+        $0 "$arg_jv" -r ${tmp}str_shelf_$1 ${tmp}num_shelf_$1 -t "${targets_combined:0:-1}" &
         [ $? -ne 0 ] && end 1 || :
     fi
 }
 
-function record(){
+touch ${tmp}answer ${tmp}following_answers
+declare -a jv_shelf=()
 
+if [ $(($opt_flag&4)) != 0 ]; then 
+    pre_processed_jv="$json_value_origin"
+else
+    preProcess
+    if [ -n "$invalid" -o "$pre_processed_jv" = "$json_value" ]; then
+        json_value_origin="$pipe_input"
+        targets+=($init_arg)
+        preProcess
+        [ -n "$invalid" ] && invalidFormatError $invalid || :
+    fi
+    for i in `seq 1 ${#jv_shelf[@]}`; do
+        callThis $i >> ${tmp}following_answers_$i
+    done
+fi
+
+function record(){
+    type_of_read=${2:-$flg_on_read}
     if [ -n "$flg_direct" ]; then
         if [ $(($flg_target&1)) != 0 ]; then
             echo "$key" >> ${tmp}answered_targets
@@ -295,15 +382,15 @@ function record(){
         else : 
         fi
     else
-        if [ "$flg_on_read" = 1 -o "$flg_on_read" = 2 ]; then
+        if [ "$type_of_read" = 1 -o "$type_of_read" = 2 ]; then
             key_prefix=1
-        elif [ "$flg_on_read" = 3 ]; then
+        elif [ "$type_of_read" = 3 ]; then
             key_prefix=3
-        elif [ "$flg_on_read" = 4 ]; then
+        elif [ "$type_of_read" = 4 ]; then
             key_prefix=2
         fi
         echo ${key_prefix}${key} >> ${tmp}answer
-        if [ "$flg_on_read" = 3 ]; then
+        if [ "$type_of_read" = 3 ]; then
             output=$(r4process "$1" "$key")
             if [ $? -ne 0 ]; then
                 [ -n "$output" ] && echo "$output" || :
@@ -319,43 +406,41 @@ function record(){
     key=''
 }
 
-function readNumValue(){
-    
-    if [ -z "${json_value:$i:1}" ]; then
-        [[ "$char" =~ ^[0-9]$ ]] || invalidFormatError
-        last_idx=$(($i-$marked_idx+1))
-    elif [[ "$char" =~ ^[0-9]$ ]]; then
+function setIndexedValue(){
+    idx+=$char
+    if [[ "${json_value:$i:1}" =~ ^[0-9]$ ]]; then
+        flg_continue=1
         return 0
-    else
-        [ "$char" != ',' ] && invalidFormatError || :
-        [ -z "$1" ] && flg_force=1 || :
-        flg_state=1
-        last_idx=$(($i-$marked_idx))
     fi
-
-    num_value=${json_value:(($marked_idx-1)):$last_idx}
-    if [ -n "$1" ]; then
-        echo $num_value
-        flg_on_read=''
-    else
-        record $num_value
-    fi
+    [ -n "$1" ] && indexed_value=${num_shelf[$idx]} || indexed_value="${str_shelf[$idx]}"
+    idx=''
+    flg_continue=''
 }
 
 function restoreObjValue(){
-
-    if [ $char = '"' ]; then
-        str_idx=${json_value:$i:1}
+    if [ "$flag_on_restore" = 1 ]; then
+        setIndexedValue
+        [ -n "$flg_continue" ] && return 0 || :
+        flag_on_restore=''
         flg_continue=1
-    elif [ -n "$str_idx" ]; then
-        if [[ "${json_value:$i:1}" =~ ^[0-9]$ ]]; then
-            str_idx+=${json_value:$i:1}
-            flg_continue=1
+        obj_value+="\"$indexed_value\""
+    elif [ "$flag_on_restore" = 2 ]; then
+        setIndexedValue 1
+        [ -n "$flg_continue" ] && return 0 || :
+        flag_on_restore=''
+        flg_continue=1
+        obj_value+="$indexed_value"
+    elif [ $char = '"' ]; then
+        flag_on_restore=1
+        flg_continue=1
+    elif [[ $char =~ ^[0-9]$ ]]; then
+        setIndexedValue 1
+        if [ -n "$flg_continue" ]; then
+            flag_on_restore=2
             return 0
         fi
-        obj_value+=\"${str_shelf[$str_idx]}\"
-        str_idx=''
         flg_continue=1
+        obj_value+="$indexed_value"
     elif [ $char = 't' ]; then
         obj_value+=true
         flg_continue=1
@@ -375,41 +460,47 @@ function next(){
     flg_state=''
 }
 
+function replaceIdx(){
+    idx+=$char
+    if [[ "${json_value:$i:1}" =~ ^[0-9]$ ]]; then
+        flg_continue=1
+        return 0
+    fi
+    [ -n "$1" ] && echo ${num_shelf[$idx]} || echo ${str_shelf[$idx]}
+    idx=''
+    flg_continue=''
+    next
+}
+
 function processAarray(){
 
     flg_force='' # 1-dbq/2-comma
     flg_state=1 # 1-distinguish value/2-extract value
     flg_on_read='' # 1-str/2-num/3-array or obj
     marked_idx=0
-    key=''
-    depth_counter=''
+    key=''; depth_counter='';
+    flag_on_restore='' # 1-str/2-num
 
     for i in `seq 1 ${#json_value}`; do
-    
         char=${json_value:(($i-1)):1}
-
         if [ -n "$flg_force" ]; then
-
             if [ "$flg_force" = 1 ]; then
-                [ "$char" != '"' ] && invalidFormatError || :
+                [ "$char" != '"' ] && invalidFormatError $i || :
                 flg_force=''
                 flg_on_read=1
             elif [ "$flg_force" = 2 ]; then
-                [ "$char" != ',' ] && invalidFormatError || :
+                [ "$char" != ',' ] && invalidFormatError $i || :
                 flg_force=''
                 flg_state=1
             fi
-        
         elif [ "$flg_state" = 1 ]; then
-            
             marked_idx=$i
             flg_state=2
-            
             if [ "$char" = '"' ]; then
                 flg_on_read=1
             elif [[ "$char" =~ ^[0-9]$ ]]; then
-                readNumValue 1
-                flg_on_read=2
+                replaceIdx 1
+                [ -n "$flg_continue" ] && flg_on_read=2 || :
             elif [ "$char" = '{' ]; then
                 flg_on_read=3
                 depth_counter='{'
@@ -430,33 +521,20 @@ function processAarray(){
             else
                 invalidFormatError
             fi
-
         elif [ "$flg_on_read" = 1 ]; then
-
-            str_idx+=$char
-            [[ "${json_value:$i:1}" =~ ^[0-9]$ ]] && continue || :
-            echo ${str_shelf[$str_idx]}
-            str_idx=''
-
-            flg_on_read=''
-            next
-            
+            replaceIdx
+            [ -z "$flg_continue" ] && flg_on_read='' || :
         elif [ "$flg_on_read" = 2 ]; then
-            
-            readNumValue 1
-
+            replaceIdx 1
+            [ -z "$flg_continue" ] && flg_on_read='' || :
         elif [ "$flg_on_read" = 3 ]; then
-
             flg_continue=''
             restoreObjValue
             [ -n "$flg_continue" ] && continue || :
-
             identifyBracket
             [ -n "$flg_continue" ] && continue || :
-            
             flg_on_read=''
             [ "$flg_state" = 2 ] && next || :
-
             echo "$obj_value"
             obj_value=''
         fi
@@ -465,19 +543,14 @@ function processAarray(){
 
 function r4process(){
 
-    json_value=$1
+    json_value=${1:1:((${#1}-2))}
     layer=$2
 
-    char_start=${json_value:0:1}
-    char_end=${json_value: -1}
-    json_value=${json_value:1:((${#json_value}-2))}
-
-    if [ "$char_start" = '{' ]; then
-        [ "$char_end" != '}' ] && invalidFormatError || :
-    elif [ "$char_start" = '[' ]; then
-        [ "$char_end" = ']' ] && flg_array=1 || invalidFormatError
+    if [ "${1:0:1}" = '{' ]; then
+        [ "${1: -1}" != '}' ] && invalidFormatError || :
+    elif [ "${1:0:1}" = '[' ]; then
+        [ "${1: -1}" = ']' ] && flg_array=1 || invalidFormatError
     fi
-
     [ -z "$json_value" ] && return 0 || :
     if [ -n "$flg_array" ]; then
         processAarray
@@ -489,15 +562,12 @@ function r4process(){
     flg_on_read='' # 1-str/2-num/3-obj/4-array
     flg_target=0 # 1-this is the target./2-including the target as children./3-both.
     marked_idx=0
-    key=''
-    depth_counter=''
+    key=''; depth_counter='';
+    flag_on_restore='' # 1-str/2-num
 
     for i in `seq 1 ${#json_value}`; do
-    
         char=${json_value:(($i-1)):1}
-
         if [ -n "$flg_force" ]; then
-
             if [ "$flg_force" = 1 ]; then
                 [ "$char" != '"' ] && invalidFormatError $i || :
                 flg_force=''
@@ -511,17 +581,19 @@ function r4process(){
                 flg_force=''
                 flg_state=2
             fi
-        
         elif [ "$flg_state" = 2 ]; then
-            
             marked_idx=$i
             flg_state=3
-            
             if [ "$char" = '"' ]; then
                 flg_on_read=1
             elif [[ "$char" =~ ^[0-9]$ ]]; then
-                readNumValue
-                flg_on_read=2
+                setIndexedValue 1
+                if [ -n "$flg_continue" ]; then
+                    flg_on_read=2
+                    continue
+                fi
+                next
+                record "$indexed_value" 2
             elif [ "$char" = '{' ]; then
                 flg_on_read=3
                 depth_counter='{'
@@ -532,146 +604,70 @@ function r4process(){
                 obj_value='['
             elif [ "$char" = 't' ]; then
                 next 
-                record true
+                record true 1
             elif [ "$char" = 'f' ]; then
                 next 
-                record false
+                record false 1
             elif [ "$char" = 'n' ]; then
                 next 
-                record null
+                record null 1
             else
                 invalidFormatError
             fi
-
         elif [ "$flg_on_read" = 1 ]; then
-
-            str_idx+=$char
-            [[ "${json_value:$i:1}" =~ ^[0-9]$ ]] && continue || :
-            str_value=${str_shelf[$str_idx]}
-            str_idx=''
-
+            setIndexedValue
+            [ -n "$flg_continue" ] && continue || :
             if [ "$flg_state" = 1 ]; then
-    
                 flg_force=3
                 flg_on_read=''
-                str_value=${str_value//./\\.}
+                str_value=${indexed_value//./\\.}; str_value=${str_value//,/\\,};
                 [ "$layer" = 'root' ] && key=$str_value || key=${layer}.${str_value}
                 [ -z "$flg_direct" ] && continue || :
-    
-                for target in ${targets[@]}; do
+                for target in "${targets[@]}"; do
                     if [ "$target" = "$key" ]; then
                         flg_target=$(($flg_target|1))
                     elif [[ "$target" =~ ^("$key").+$ ]]; then
                         flg_target=$(($flg_target|2))
                     fi
-                done
-    
+                done    
             elif [ "$flg_state" = 3 ]; then
                 next
-                record "$str_value"
+                record "$indexed_value"
             fi
-
         elif [ "$flg_on_read" = 2 ]; then
-            
-            readNumValue
-
+            setIndexedValue 1
+            [ -n "$flg_continue" ] && continue || :
+            next
+            record "$indexed_value"
         elif [ "$flg_on_read" = 3 -o "$flg_on_read" = 4 ]; then
-
             flg_continue=''
             if [ "$flg_on_read" = 3 -a $(($flg_target&1)) != 0 ]; then
                 restoreObjValue
                 [ -n "$flg_continue" ] && continue || :
             fi
-
             identifyBracket
             [ -n "$flg_continue" ] && continue || :
-            
             indexed_obj_value="${json_value:(($marked_idx-1)):(($i-$marked_idx+1))}"
             [ "${#indexed_obj_value}" = 2 ] && empty=1 || :
-
             if [ -z "$flg_direct" -a "$flg_on_read" = 3 ]; then
                 obj_value="$indexed_obj_value"
-
             elif [ -z "$flg_direct" -a "$flg_on_read" = 4 -o \
                  "$flg_on_read" = 3 -a $(($flg_target&2)) != 0 -o \
                  "$flg_on_read" = 4 -a $(($flg_target&1)) != 0 ]; then
-
                 output=$(r4process "$indexed_obj_value" "$key")
                 if [ $? -ne 0 ]; then
                     [ -n "$output" ] && echo "$output" || :
                     end 1
-                fi
-                
+                fi  
                 [ "$flg_on_read" = 4 ] && obj_value="$output" || :
             fi
-
             [ "$flg_state" = 3 ] && next || :
-
             record "$obj_value"
             obj_value=''
             empty=''
         fi
     done
 }
-
-declare -a targets=()
-declare -a str_shelf=()
-opt_flag=0 # 1-compget/2-checkerr/4-recursive
-init_arg=''
-rcount=0
-argext_flag='' # 1-target/2-recursive
-
-if [ -p /dev/stdin ]; then
-    pipe_input="$(cat)"
-fi
-
-for arg in "$@"; do
-    if [ -n "$argext_flag" ]; then
-        if [ "$argext_flag" = 1 ]; then
-            setTargets "$arg"
-        elif [ "$argext_flag" = 2 ]; then
-            while read str; do 
-                str=${str//$CR/}
-                str=${str//$LF/}
-                str_shelf+=("$str")
-            done < <(cat "$arg")
-        fi
-        argext_flag=''
-    elif [[ "$arg" =~ ^-.+ ]]; then
-        processShortOpt "$arg"
-    elif [ -z "$init_arg" ]; then
-        init_arg="$arg"
-    fi
-done
-
-if [ -f "$init_arg" ]; then
-    json_value_origin="$(cat $init_arg)"
-else
-    json_value_origin="$init_arg"
-fi    
-
-if [ $(($opt_flag&1)) != 0 ]; then
-    extractValue
-    end 0
-fi
-
-touch ${tmp}answer ${tmp}following_answers
-declare -a jv_shelf=()
-
-if [ $(($opt_flag&4)) != 0 ]; then 
-    pre_processed_jv="$json_value_origin"
-else
-    preProcess
-    if [ -n "$invalid" -o "$pre_processed_jv" = "$json_value" ]; then
-        json_value_origin="$pipe_input"
-        targets+=($init_arg)
-        preProcess
-        [ -n "$invalid" ] && invalidFormatError $invalid || :
-    fi
-    for i in `seq 1 ${#jv_shelf[@]}`; do
-        callThis $i >> ${tmp}following_answers_$i
-    done
-fi
 
 [ ${#targets[@]} -ne 0 ] && flg_direct=1 || :
 
